name: Deploy Nginx

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Ermöglicht manuelles Triggern des Workflows über GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

      - name: Setup Ansible
        uses: dawidd6/action-ansible@v2
        with:
          ansible-version: 2.12

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
        run: |
          ansible-playbook ansible/nginx-playbook.yml -i ansible/inventory.ini --private-key ~/.ssh/ec2-key.pem
